# Generated by Django 6.1.1 on 2026-09-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
